name: CustomWings
api: 4.0.0
version: 1.5
main: CustomWings\Main
author: ItzBluee02
commands:
  customwings:
    description: "CustomWings"
    usage: /customwings
    permission: customwings.use
    aliases: [cw, wings]
permissions:
  customwings.use:
    default: true